### ISSUE TITLE
e-mails from Speedport Smart 4: "a security-related event has occured" - please add info to README

### ISSUE THREAD

**Issue by DFS-90** [Andre0512/speedport#1]
Hi,

thank you for providing this amazing add-on! 👍 

After adding it to HACS, I realized that I got a lot of e-mails from my router, saying that "A security-related event has occured".
This e-mail is sent every time a successful login has taken place.

After unchecking the following setting, it stopped immediately:

German:
![Screenshot 2023-10-16 101013](https://github.com/Andre0512/speedport/assets/87578070/f9a53879-1d55-4de8-a2f6-5c34085baf7f)

English:
![Screenshot 2023-10-16 182544](https://github.com/Andre0512/speedport/assets/87578070/44a0b5a1-d4f9-42fd-9389-0759282b73b7)

Maybe you want to add this info to README?

Thanks and best regards,
David

**Comment by Andre0512** [comment]
Hi, thanks for testing! :slightly_smiling_face: 
That's a good hint, I added it to the README.
