### ISSUE TITLE
Connection on Port 80, although https is enabled

### ISSUE THREAD

**Issue by fightforlife** [Andre0512/speedport#10]
I set up this integration with https enabled in the router and in the integration.
The initial config flow is successful, but no data is fetched from the router.
The debug logs show that the integration is trying to access the router web interface on port 80.
But it should be port 443 when https is selected.

When disabling https  on the router side it works.

**Comment by MarsellusW** [comment]
I'm facing the same issue!
Disabling https at router side works but is not really an option... ;-)

> Logger: homeassistant.config_entries
> Source: config_entries.py:406
> First occurred: 4. Januar 2024 um 00:40:39 (3 occurrences)
> Last logged: 4. Januar 2024 um 00:45:44
> 
> Error setting up entry Speedport for speedport
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
>     return await self._loop.create_connection(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
>     raise exceptions[0]
>   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
>     sock = await self._connect_sock(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
>     await self.sock_connect(sock, address)
>   File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
>     return await fut
>            ^^^^^^^^^
>   File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
>     raise OSError(err, f'Connect call failed {address}')
> ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.2.1', 80)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/speedport/__init__.py", line 26, in async_setup_entry
>     speedport = await Speedport(
>                 ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/speedport/speedport.py", line 60, in create
>     await self.update_status()
>   File "/usr/local/lib/python3.11/site-packages/speedport/speedport.py", line 118, in update_status
>     self._status = await self.api.get_status()
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/speedport/api.py", line 116, in get_status
>     return await self.api.get("data/Status.json")
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/speedport/connection.py", line 94, in get
>     async with self._session.get(url, headers={"Referer": referer}) as response:
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
>     self._resp = await self._coro
>                  ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 574, in _request
>     conn = await self._connector.connect(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
>     proto = await self._create_connection(req, traces, timeout)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
>     _, proto = await self._create_direct_connection(req, traces, timeout)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
>     raise last_exc
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
>     transp, proto = await self._wrap_create_connection(
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
>     raise client_error(req.connection_key, exc) from exc
> aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.2.1:80 ssl:default [Connect call failed ('192.168.2.1', 80)]

**Comment by eeeeb** [comment]
Hello, if I read my logs correctly I think I am running into the same issue with port 80.
I installed the integration through HACS, and then added/configured it in devices and integrations to use the IP 10.10.1.1 and HTTPS. 
But when I look at the integration in settings > devices and integrations the Speedport integration states: Failed to set up
In the Speedport logs I see that a login was successful for the time of the set up of the Speedport integration.

As a side note, the Speedport is on the subnet 10.10.1.0/24 while my Home Assistant is on 10.10.10.0/24 but I can log into the Speedport from HA, as I stated above and can also ping the Speedport from HA.

```
Logger: homeassistant.config_entries
Source: config_entries.py:444
First occurred: 10:11:52 (3 occurrences)
Last logged: 10:37:11

Error setting up entry Speedport for speedport
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1119, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1101, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1004, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 637, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 677, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('10.10.1.1', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/speedport/__init__.py", line 26, in async_setup_entry
    speedport = await Speedport(
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/speedport/speedport.py", line 60, in create
    await self.update_status()
  File "/usr/local/lib/python3.12/site-packages/speedport/speedport.py", line 118, in update_status
    self._status = await self.api.get_status()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/speedport/api.py", line 116, in get_status
    return await self.api.get("data/Status.json")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/speedport/connection.py", line 94, in get
    async with self._session.get(url, headers={"Referer": referer}) as response:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 10.10.1.1:80 ssl:default [Connect call failed ('10.10.1.1', 80)]
```

I am using 
* Speedport Smart 4 Typ A - Firmware version: 010139.3.4.001.1
* Speedport integration: 0.3.3
* Home Assistant
** Core: 2024.2.1
** Supervisor: 2024.01.1
** Operating System: 11.5
** Frontend: 20240207.1

**Comment by Andre0512** [comment]
Hi, this setting seems to have been ignored, it should work now.
