### ISSUE TITLE
Use Web UI from speedport is not working

### ISSUE THREAD

**Issue by MelleD** [Andre0512/speedport#5]
Thanks for the integration 🚀 🚀 🚀 

I found a problem, when I use the integration I can no longer use the "normal" http://speedport.ip/ because I get logged out all the time.

Is that the case with you too?

**Comment by MelleD** [comment]
Sorry my mistake: 

Duplicated see here: https://github.com/Andre0512/speedport/issues/2

**Comment by Andre0512** [comment]
Thanks for testing! 🙂
