### ISSUE TITLE
[BUG] False default unit for download / upload

### ISSUE THREAD

**Issue by jafhueppe** [Andre0512/speedport#8]
Hey there,

I'm using your plugin with a Speedport 4 and I get the wrong value because of a false default unit, maybe here https://github.com/Andre0512/speedport/blob/main/custom_components/speedport/sensor.py#L43

I have a download speed from ~250 mBit/s but your plugin shows 250.000 MBit/s, a thousand times more than expected.

HA Version: 2023.11.2
Speedport 4
Speedport firmware: 010146.3.3.001.2

Do you need further information? Please let me know!

Thank you very much for the plugin and your work, it's awesome!

**Comment by Andre0512** [comment]
Hey, fixed! Thanks for reporting :slightly_smiling_face:

**Comment by jafhueppe** [comment]
The issue is still there.. I even downloaded your plugin again..

I saw the latest release is before this issue was solved, Do you need to create a New one?

**Comment by jafhueppe** [comment]
Hey @Andre0512 

Do you have an update for me?
